///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
String formatCnpj(String cnpj) {
  // Remover caracteres não numéricos
  cnpj = cnpj.replaceAll(RegExp(r'\D'), '');

  // Garantir que o CNPJ tenha 14 dígitos
  if (cnpj.length != 14) {
    return 'CNPJ inválido';
  }

  // Formatar o CNPJ
  return "${cnpj.substring(0, 2)}.${cnpj.substring(2, 5)}.${cnpj.substring(5, 8)}/${cnpj.substring(8, 12)}-${cnpj.substring(12)}";
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelEmpresas {
/*
{
  "guid": "6EC7AC88F41876EC6FAED754C7C438323D5A",
  "uciduser": "736",
  "empresa": "Medcore",
  "cnpj": "2"
} 
*/

  String? guid;
  String? uciduser;
  String? empresa;
  String? cnpj;

  LoginModelEmpresas({
    this.guid,
    this.uciduser,
    this.empresa,
    this.cnpj,
  });
  LoginModelEmpresas.fromJson(Map<String, dynamic> json) {
    guid = json['guid']?.toString();
    uciduser = json['uciduser']?.toString();
    empresa = json['empresa']?.toString();
    cnpj = formatCnpj(json['cnpj']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['guid'] = guid;
    data['uciduser'] = uciduser;
    data['empresa'] = empresa;
    data['cnpj'] = cnpj;
    return data;
  }
}

class LoginModel {
/*
{
  "success": true,
  "ucusername": "Lucival da Silva Cruz",
  "uclogin": "lucivalsc",
  "ucemail": "lucivalsc@gmail.com",
  "empresas": [
    {
      "guid": "6EC7AC88F41876EC6FAED754C7C438323D5A",
      "uciduser": "736",
      "empresa": "Medcore",
      "cnpj": "2"
    }
  ]
} 
*/

  bool? success;
  String? ucusername;
  String? uclogin;
  String? ucemail;
  List<LoginModelEmpresas?>? empresas;

  LoginModel({
    this.success,
    this.ucusername,
    this.uclogin,
    this.ucemail,
    this.empresas,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    ucusername = json['ucusername']?.toString();
    uclogin = json['uclogin']?.toString();
    ucemail = json['ucemail']?.toString();
    if (json['empresas'] != null) {
      final v = json['empresas'];
      final arr0 = <LoginModelEmpresas>[];
      v.forEach((v) {
        arr0.add(LoginModelEmpresas.fromJson(v));
      });
      empresas = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['ucusername'] = ucusername;
    data['uclogin'] = uclogin;
    data['ucemail'] = ucemail;
    if (empresas != null) {
      final v = empresas;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['empresas'] = arr0;
    }
    return data;
  }
}
