///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UsuarioModel {
/*
{
  "user": "mecgestao@teste.com",
  "password": "1234"
} 
*/

  String? user;
  String? password;

  UsuarioModel({
    this.user,
    this.password,
  });
  UsuarioModel.fromJson(Map<String, dynamic> json) {
    user = json['user']?.toString();
    password = json['password']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    data['password'] = password;
    return data;
  }
}
