///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class YearLinesModelAnoAnteriorDois {
  int? dia;
  int? mes;
  int? ano;
  String? descricao;
  String? valor;

  YearLinesModelAnoAnteriorDois({
    this.dia,
    this.mes,
    this.ano,
    this.descricao,
    this.valor,
  });
  YearLinesModelAnoAnteriorDois.fromJson(Map<String, dynamic> json) {
    dia = json['dia']?.toInt();
    mes = json['mes']?.toInt();
    ano = json['ano']?.toInt();
    descricao = json['descricao']?.toString();
    valor = json['valor']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['dia'] = dia;
    data['mes'] = mes;
    data['ano'] = ano;
    data['descricao'] = descricao;
    data['valor'] = valor;
    return data;
  }
}

class YearLinesModelAnoAnterior {
  int? dia;
  int? mes;
  int? ano;
  String? descricao;
  String? valor;

  YearLinesModelAnoAnterior({
    this.dia,
    this.mes,
    this.ano,
    this.descricao,
    this.valor,
  });
  YearLinesModelAnoAnterior.fromJson(Map<String, dynamic> json) {
    dia = json['dia']?.toInt();
    mes = json['mes']?.toInt();
    ano = json['ano']?.toInt();
    descricao = json['descricao']?.toString();
    valor = json['valor']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['dia'] = dia;
    data['mes'] = mes;
    data['ano'] = ano;
    data['descricao'] = descricao;
    data['valor'] = valor;
    return data;
  }
}

class YearLinesModelAnoAtual {
  int? dia;
  int? mes;
  int? ano;
  String? descricao;
  String? valor;

  YearLinesModelAnoAtual({
    this.dia,
    this.mes,
    this.ano,
    this.descricao,
    this.valor,
  });
  YearLinesModelAnoAtual.fromJson(Map<String, dynamic> json) {
    dia = json['dia']?.toInt();
    mes = json['mes']?.toInt();
    ano = json['ano']?.toInt();
    descricao = json['descricao']?.toString();
    valor = json['valor']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['dia'] = dia;
    data['mes'] = mes;
    data['ano'] = ano;
    data['descricao'] = descricao;
    data['valor'] = valor;
    return data;
  }
}

class YearLinesModel {
  List<YearLinesModelAnoAtual?>? anoAtual;
  List<YearLinesModelAnoAnterior?>? anoAnterior;
  List<YearLinesModelAnoAnteriorDois?>? anoAnteriorDois;

  YearLinesModel({
    this.anoAtual,
    this.anoAnterior,
    this.anoAnteriorDois,
  });
  YearLinesModel.fromJson(Map<String, dynamic> json) {
    if (json['ano_atual'] != null) {
      final v = json['ano_atual'];
      final arr0 = <YearLinesModelAnoAtual>[];
      v.forEach((v) {
        arr0.add(YearLinesModelAnoAtual.fromJson(v));
      });
      anoAtual = arr0;
    }
    if (json['ano_anterior'] != null) {
      final v = json['ano_anterior'];
      final arr0 = <YearLinesModelAnoAnterior>[];
      v.forEach((v) {
        arr0.add(YearLinesModelAnoAnterior.fromJson(v));
      });
      anoAnterior = arr0;
    }
    if (json['ano_anterior_dois'] != null) {
      final v = json['ano_anterior_dois'];
      final arr0 = <YearLinesModelAnoAnteriorDois>[];
      v.forEach((v) {
        arr0.add(YearLinesModelAnoAnteriorDois.fromJson(v));
      });
      anoAnteriorDois = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (anoAtual != null) {
      final v = anoAtual;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['ano_atual'] = arr0;
    }
    if (anoAnterior != null) {
      final v = anoAnterior;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['ano_anterior'] = arr0;
    }
    if (anoAnteriorDois != null) {
      final v = anoAnteriorDois;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['ano_anterior_dois'] = arr0;
    }
    return data;
  }
}
