///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReportModelUndefined {
/*
{
  "tipo": "Administra��o",
  "descricao": "NÃO DIGITADO",
  "total": "1"
} 
*/

  String? tipo;
  String? descricao;
  String? total;

  ReportModelUndefined({
    this.tipo,
    this.descricao,
    this.total,
  });
  ReportModelUndefined.fromJson(Map<String, dynamic> json) {
    tipo = json['tipo']?.toString();
    descricao = json['descricao']?.toString();
    total = json['total']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['tipo'] = tipo;
    data['descricao'] = descricao;
    data['total'] = total;
    return data;
  }
}

class ReportModel {
/*
{
  "undefined": [
    {
      "tipo": "Administra��o",
      "descricao": "NÃO DIGITADO",
      "total": "1"
    }
  ]
} 
*/

  List<ReportModelUndefined?>? undefined;

  ReportModel({
    this.undefined,
  });
  ReportModel.fromJson(Map<String, dynamic> json) {
    if (json['undefined'] != null) {
      final v = json['undefined'];
      final arr0 = <ReportModelUndefined>[];
      v.forEach((v) {
        arr0.add(ReportModelUndefined.fromJson(v));
      });
      undefined = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (undefined != null) {
      final v = undefined;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['undefined'] = arr0;
    }
    return data;
  }
}
